
CREATE TABLE payment_details (
    payment_record_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    amount NUMBER NOT NULL,
    status VARCHAR2(150) NOT NULL,
    payment_date DATE ,
    payment_time TIMESTAMP ,
    receptionist_id NUMBER ,
    patient_id NUMBER NOT NULL,
    PRIMARY KEY (payment_record_id),
    FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
    FOREIGN KEY (receptionist_id) REFERENCES receptionist(receptionist_id)
);

CREATE TABLE doctor_patient_consult_details (
    patient_id NUMBER,
    doctor_id NUMBER,
    PRIMARY KEY(patient_id, doctor_id),
    FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
);

CREATE TABLE medical_records(
    medical_record_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    age NUMBER,
    disease VARCHAR2(100) NOT NULL,
    medication VARCHAR2(120),
    PRIMARY KEY (medical_record_id)
);

CREATE TABLE patient_medical_records(
    patient_id NUMBER NOT NULL,
    medical_record_id NUMBER NOT NULL,
    PRIMARY KEY (patient_id, medical_record_id),
    FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
    FOREIGN KEY (medical_record_id) REFERENCES medical_records(medical_record_id)
);

CREATE TABLE symptoms_record(
    medical_record_id NUMBER NOT NULL,
    symptom VARCHAR2(150)NOT NULL,
    PRIMARY KEY (medical_record_id, symptom),
    FOREIGN KEY (medical_record_id) REFERENCES medical_records(medical_record_id)
);

COMMIT WORK;
